// apps/mobile/app/login.tsx
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Redirect, router } from "expo-router";
import { useState } from "react";
import { login } from "@/features/auth/api";
import { AuthScreen } from "@/features/auth/components/auth-screen";
import { authKeys } from "@/features/auth/keys";
import { useAuthStatus } from "@/features/auth/use-auth-status";
import { RecorderLink } from "@/features/server/components/recorder-link";
import { ApiError } from "@/lib/api/error";

export default function LoginScreen() {
	const queryClient = useQueryClient();
	const auth = useAuthStatus();
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const [error, setError] = useState<string | null>(null);

	const loginMutation = useMutation({
		mutationFn: () => login({ username: username.trim(), password }),
		onSuccess: async () => {
			setError(null);
			await queryClient.invalidateQueries({ queryKey: authKeys.all });
			router.replace("/(tabs)/(live)");
		},
		onError: (err: unknown) => {
			if (err instanceof ApiError) {
				setError(err.message);
				return;
			}
			setError(err instanceof Error ? err.message : "Login failed");
		},
	});

	if (auth.isSuccess && auth.data.setupRequired) {
		return <Redirect href="/setup" />;
	}
	if (auth.isSuccess && auth.data.user) {
		return <Redirect href="/(tabs)/(live)" />;
	}

	return (
		<AuthScreen
			description="Sign in with the same account you use on the web dashboard."
			error={error}
			footer={<RecorderLink />}
			onPasswordChange={setPassword}
			onSubmit={() => {
				setError(null);
				loginMutation.mutate();
			}}
			onUsernameChange={setUsername}
			password={password}
			submitLabel="Sign in"
			submitting={loginMutation.isPending}
			title="Sign in"
			username={username}
		/>
	);
}

// apps/dashboard/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import { createMutation, useQueryClient } from "@tanstack/svelte-query";
	import {
		AuthApiError,
		authKeys,
		login as loginRequest,
		type LoginFormValues,
	} from "$lib/auth";
	import AuthCard from "$lib/components/AuthCard.svelte";
	import LoginForm from "$lib/components/forms/LoginForm.svelte";

	const queryClient = useQueryClient();

	let serverError = $state<string | null>(null);

	const loginMutation = createMutation(() => ({
		mutationFn: (values: LoginFormValues) => loginRequest(values),
		onSuccess: async () => {
			serverError = null;
			await queryClient.invalidateQueries({ queryKey: authKeys.all });
			await goto("/");
		},
		onError: (error: unknown) => {
			if (error instanceof AuthApiError) {
				serverError = error.message;
				return;
			}
			serverError = error instanceof Error ? error.message : "Login failed";
		},
	}));

	async function handleSubmit(values: LoginFormValues) {
		serverError = null;
		await loginMutation.mutateAsync(values);
	}
</script>

<svelte:head>
	<title>Sign in · NVR</title>
</svelte:head>

<AuthCard title="Sign in" description="Access your NVR dashboard with your account credentials.">
	<LoginForm
		submitting={loginMutation.isPending}
		serverError={serverError}
		onSubmit={handleSubmit}
	/>
</AuthCard>
